# Copyright (C) 2010 The Android Open Source Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/bn/encore/extract-files.sh - DO NOT EDIT

PRODUCT_COPY_FILES += \
    vendor/bn/encore/prebuilt/liba2dp.so:/system/lib/liba2dp.so \
    vendor/bn/encore/prebuilt/libasound.so:/system/lib/libasound.so \
    vendor/bn/encore/prebuilt/libaudiopolicy.so:/system/lib/libaudiopolicy.so \
    vendor/bn/encore/prebuilt/libaudio.so:/system/lib/libaudio.so \
    vendor/bn/encore/prebuilt/alsa.omap3.so:/system/lib/hw/alsa.omap3.so \
    vendor/bn/encore/prebuilt/alsa.conf:/system/usr/share/alsa/alsa.conf \
    vendor/bn/encore/prebuilt/aliases.conf:/system/usr/share/alsa/cards/aliases.conf \
    vendor/bn/encore/prebuilt/00main:/system/usr/share/alsa/init/00main \
    vendor/bn/encore/prebuilt/default:/system/usr/share/alsa/init/default \
    vendor/bn/encore/prebuilt/hda:/system/usr/share/alsa/init/hda \
    vendor/bn/encore/prebuilt/help:/system/usr/share/alsa/init/help \
    vendor/bn/encore/prebuilt/info:/system/usr/share/alsa/init/info \
    vendor/bn/encore/prebuilt/test:/system/usr/share/alsa/init/test \
    vendor/bn/encore/prebuilt/center_lfe.conf:/system/usr/share/alsa/pcm/center_lfe.conf \
    vendor/bn/encore/prebuilt/default.conf:/system/usr/share/alsa/pcm/default.conf \
    vendor/bn/encore/prebuilt/dmix.conf:/system/usr/share/alsa/pcm/dmix.conf \
    vendor/bn/encore/prebuilt/dpl.conf:/system/usr/share/alsa/pcm/dpl.conf \
    vendor/bn/encore/prebuilt/dsnoop.conf:/system/usr/share/alsa/pcm/dsnoop.conf \
    vendor/bn/encore/prebuilt/front.conf:/system/usr/share/alsa/pcm/front.conf \
    vendor/bn/encore/prebuilt/iec958.conf:/system/usr/share/alsa/pcm/iec958.conf \
    vendor/bn/encore/prebuilt/modem.conf:/system/usr/share/alsa/pcm/modem.conf \
    vendor/bn/encore/prebuilt/rear.conf:/system/usr/share/alsa/pcm/rear.conf \
    vendor/bn/encore/prebuilt/side.conf:/system/usr/share/alsa/pcm/side.conf \
    vendor/bn/encore/prebuilt/surround40.conf:/system/usr/share/alsa/pcm/surround40.conf \
    vendor/bn/encore/prebuilt/surround41.conf:/system/usr/share/alsa/pcm/surround41.conf \
    vendor/bn/encore/prebuilt/surround50.conf:/system/usr/share/alsa/pcm/surround50.conf \
    vendor/bn/encore/prebuilt/surround51.conf:/system/usr/share/alsa/pcm/surround51.conf \
    vendor/bn/encore/prebuilt/surround71.conf:/system/usr/share/alsa/pcm/surround71.conf
