# Copyright (C) 2013 The Android Open Source Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/bn/hd-common/setup-makefiles.sh

PRODUCT_COPY_FILES += \
    vendor/bn/hd-common/proprietary/vendor/firmware/ducati-m3.bin:system/vendor/firmware/ducati-m3.bin \
    vendor/bn/hd-common/proprietary/vendor/firmware/smc_pa.ift:system/vendor/firmware/smc_pa.ift \
   vendor/bn/hd-common/proprietary/bin/install_wv_keybox:/system/bin/install_wv_keybox \
   vendor/bn/hd-common/proprietary/bin/wvdrm_test_client:/system/bin/wvdrm_test_client \
   vendor/bn/hd-common/proprietary/lib/libion.so:/system/lib/libion.so \
    vendor/bn/hd-common/proprietary/vendor/firmware/TIInit_7.6.15.bts:system/etc/firmware/TIInit_7.6.15.bts \
    vendor/bn/hd-common/proprietary/vendor/firmware/wl1271-nvs_127x.bin:system/etc/firmware/ti-connectivity/wl1271-nvs.bin.orig \
    vendor/bn/hd-common/proprietary/vendor/firmware/wl127x-fw-4-mr.bin:system/etc/firmware/ti-connectivity/wl127x-fw-4-mr.bin \
    vendor/bn/hd-common/proprietary/vendor/firmware/wl127x-fw-4-plt.bin:system/etc/firmware/ti-connectivity/wl127x-fw-4-plt.bin \
    vendor/bn/hd-common/proprietary/vendor/firmware/wl127x-fw-4-sr.bin:system/etc/firmware/ti-connectivity/wl127x-fw-4-sr.bin \
    vendor/bn/hd-common/proprietary/vendor/firmware/ini_files/RFMD_D_E5.ini:system/etc/firmware/ti-connectivity/ini_files/RFMD_D_E5.ini \
    vendor/bn/hd-common/proprietary/vendor/firmware/ini_files/RFMD_S_3.5.ini:system/etc/firmware/ti-connectivity/ini_files/RFMD_S_3.5.ini \
    vendor/bn/hd-common/proprietary/vendor/firmware/ini_files/TQS_D_1.0.ini:system/etc/firmware/ti-connectivity/ini_files/TQS_D_1.0.ini \
    vendor/bn/hd-common/proprietary/vendor/firmware/ini_files/TQS_D_1.7.ini:system/etc/firmware/ti-connectivity/ini_files/TQS_D_1.7.ini \
    vendor/bn/hd-common/proprietary/vendor/firmware/ini_files/TQS_S_2.5.ini:system/etc/firmware/ti-connectivity/ini_files/TQS_S_2.5.ini \
    vendor/bn/hd-common/proprietary/vendor/firmware/ini_files/TQS_S_2.6.ini:system/etc/firmware/ti-connectivity/ini_files/TQS_S_2.6.ini \


