# Copyright (C) 2013 The Android Open Source Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/bn/acclaim/setup-makefiles.sh

PRODUCT_COPY_FILES += \
 vendor/bn/acclaim/proprietary/xbin/setpropex:system/xbin/setpropex \
 vendor/bn/acclaim/proprietary/bin/bbx:system/bin/bbx \
 vendor/bn/acclaim/proprietary/etc/firmware/ti-connectivity/LICENSE:system/etc/firmware/ti-connectivity/LICENSE \
 vendor/bn/acclaim/proprietary/etc/firmware/ti-connectivity/wl1271-nvs_127x.bin:system/etc/firmware/ti-connectivity/wl1271-nvs_127x.bin \
 vendor/bn/acclaim/proprietary/etc/firmware/ti-connectivity/wl127x-fw-4-mr.bin:system/etc/firmware/ti-connectivity/wl127x-fw-4-mr.bin \
 vendor/bn/acclaim/proprietary/etc/firmware/ti-connectivity/wl127x-fw-4-plt.bin:system/etc/firmware/ti-connectivity/wl127x-fw-4-plt.bin \
 vendor/bn/acclaim/proprietary/etc/firmware/ti-connectivity/wl127x-fw-4-sr.bin:system/etc/firmware/ti-connectivity/wl127x-fw-4-sr.bin \
 vendor/bn/acclaim/proprietary/etc/wifi/TQS_S_2.6.ini:system/etc/wifi/TQS_S_2.6.ini \
 vendor/bn/acclaim/proprietary/etc/firmware/touch/ft5406_sc3052_1024x768.bin:system/etc/firmware/touch/ft5406_sc3052_1024x768.bin \
 vendor/bn/acclaim/proprietary/etc/firmware/touch/fts0019u700_ver13_app.bin:system/etc/firmware/touch/fts0019u700_ver13_app.bin \
 vendor/bn/acclaim/proprietary/etc/firmware/touch/fts0019u700_ver14_app.bin:system/etc/firmware/touch/fts0019u700_ver14_app.bin \
 vendor/bn/acclaim/proprietary/etc/firmware/ducati-license.txt:system/etc/firmware/ducati-license.txt \
 vendor/bn/acclaim/proprietary/etc/firmware/ducati-m3.512MB.bin:system/etc/firmware/ducati-m3.512MB.bin \
 vendor/bn/acclaim/proprietary/etc/firmware/ducati-m3.bin:system/etc/firmware/ducati-m3.bin
