# Copyright (C) 2013 The Android Open Source Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/bn/acclaim/setup-makefiles.sh

PRODUCT_COPY_FILES += \
 vendor/bn/acclaim/proprietary/etc/firmware/touch/ft5406_sc3052_1024x768.bin:system/etc/firmware/touch/ft5406_sc3052_1024x768.bin \
 vendor/bn/acclaim/proprietary/etc/firmware/touch/fts0019u700_ver13_app.bin:system/etc/firmware/touch/fts0019u700_ver13_app.bin \
 vendor/bn/acclaim/proprietary/etc/firmware/touch/fts0019u700_ver14_app.bin:system/etc/firmware/touch/fts0019u700_ver14_app.bin \
 vendor/bn/acclaim/proprietary/etc/firmware/ducati-license.txt:system/etc/firmware/ducati-license.txt \
 vendor/bn/acclaim/proprietary/etc/firmware/ducati-m3.512MB.bin:system/etc/firmware/ducati-m3.512MB.bin \
 vendor/bn/acclaim/proprietary/etc/firmware/ducati-m3.bin:system/etc/firmware/ducati-m3.bin \
 vendor/bn/acclaim/proprietary/vendor/lib/hw/gralloc.omap4430.so:system/vendor/lib/hw/gralloc.omap4430.so \
 vendor/bn/acclaim/proprietary/vendor/lib/egl/libEGL_POWERVR_SGX540_120.so:system/vendor/lib/egl/libEGL_POWERVR_SGX540_120.so \
 vendor/bn/acclaim/proprietary/vendor/lib/egl/libGLESv1_CM_POWERVR_SGX540_120.so:system/vendor/lib/egl/libGLESv1_CM_POWERVR_SGX540_120.so \
 vendor/bn/acclaim/proprietary/vendor/lib/egl/libGLESv2_POWERVR_SGX540_120.so:system/vendor/lib/egl/libGLESv2_POWERVR_SGX540_120.so \
 vendor/bn/acclaim/proprietary/vendor/lib/libglslcompiler_SGX540_120.so:system/vendor/lib/libglslcompiler_SGX540_120.so \
 vendor/bn/acclaim/proprietary/vendor/lib/libIMGegl_SGX540_120.so:system/vendor/lib/libIMGegl_SGX540_120.so \
 vendor/bn/acclaim/proprietary/vendor/lib/libpvr2d_SGX540_120.so:system/vendor/lib/libpvr2d_SGX540_120.so \
 vendor/bn/acclaim/proprietary/vendor/lib/libpvrANDROID_WSEGL_SGX540_120.so:system/vendor/lib/libpvrANDROID_WSEGL_SGX540_120.so \
 vendor/bn/acclaim/proprietary/vendor/lib/libPVRScopeServices_SGX540_120.so:system/vendor/lib/libPVRScopeServices_SGX540_120.so \
 vendor/bn/acclaim/proprietary/vendor/lib/libsrv_init_SGX540_120.so:system/vendor/lib/libsrv_init_SGX540_120.so \
 vendor/bn/acclaim/proprietary/vendor/lib/libsrv_um_SGX540_120.so:system/vendor/lib/libsrv_um_SGX540_120.so \
 vendor/bn/acclaim/proprietary/vendor/lib/libusc_SGX540_120.so:system/vendor/lib/libusc_SGX540_120.so \
 vendor/bn/acclaim/proprietary/etc/powervr.ini:system/etc/powervr.ini \
 vendor/bn/acclaim/proprietary/lib/libdrmdecrypt.so:system/lib/libdrmdecrypt.so \
 vendor/bn/acclaim/proprietary/vendor/lib/drm/libdrmwvmplugin.so:system/vendor/lib/drm/libdrmwvmplugin.so \
 vendor/bn/acclaim/proprietary/vendor/lib/libWVStreamControlAPI_L3.so:system/vendor/lib/libWVStreamControlAPI_L3.so \
 vendor/bn/acclaim/proprietary/vendor/lib/libwvdrm_L3.so:system/vendor/lib/libwvdrm_L3.so \
 vendor/bn/acclaim/proprietary/vendor/lib/libwvm.so:system/vendor/lib/libwvm.so \
 vendor/bn/acclaim/proprietary/vendor/lib/mediadrm/libwvdrmengine.so:system/vendor/lib/mediadrm/libwvdrmengine.so \
 vendor/bn/acclaim/proprietary/vendor/lib/libdrmmtkutil.so:system/vendor/lib/libdrmmtkutil.so
